site_name: 논문을읽어요
site_description: arXiv 논문을 매주 자동으로 골라 한국어 전문 번역으로 아카이브합니다.
theme:
  name: material
  language: ko
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: 다크 모드로 전환
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 라이트 모드로 전환
  features:
    - search.suggest
    - navigation.instant

nav:
  - 홈: index.md

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - tables
  - footnotes

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
